name: Build

on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        component: [shellcode_utils, loader, shellcode_stage1, shellcode_stage1_network, shellcode_stage2, shellcode_gen, daemon, server, test_program_rust]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly

      - name: Build ${{ matrix.component }}
        working-directory: crates/${{ matrix.component }}
        run: cargo build --release --all-features

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Binaries
          path: |
            README.md
            LICENSE
            crates/${{ matrix.component }}/target/release/${{ matrix.component }}.exe
            crates/${{ matrix.component }}/target/x86_64-pc-windows-msvc/release/${{ matrix.component }}.exe

  generate:
    name: Generate payloads
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Generate payloads
        run: |
          mkdir output
          .\crates\shellcode_gen\target\release\shellcode_gen.exe output\
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Payloads
          path: |
            output\**

  bundle:
    name: Bundle
    runs-on: windows-latest
    needs: [build, generate]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Bundle binaries
        run: tree .

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: Solstice.zip